# ~/.config/starship.toml

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
style = "bold cyan"

[git_branch]
symbol = " "

[hostname]
prefix = "@"
trim_at = ""

[nodejs]
style = "bold green"
